import type {
  ClubInfo,
  ClubCounts,
  ClubEvent,
  ClubAnnouncement,
  ClubMember,
  ClubApplication,
  TeamMember,
  ClubAchievement,
  AnalyticsData,
  GalleryItem,
} from '@/types/club';

export const MOCK_CLUB: ClubInfo = {
  id: 'mock-cie-001',
  name: 'CIE Club',
  description:
    'The Center for Innovation & Entrepreneurship (CIE) is the premier student-run innovation hub at MLRIT. We bridge the gap between academic knowledge and real-world impact by fostering a culture of creativity, problem-solving, and entrepreneurial thinking. From ideathons to industry partnerships, CIE empowers students to build, launch, and grow their ideas.',
  advisor_name: 'Dr. P. Ramesh Kumar',
  contact_email: 'cie@mlrit.ac.in',
  logo_url: '/clubs/cie-logo.png',
  is_active: true,
};

export const MOCK_COUNTS: ClubCounts = {
  members: 87,
  events: 24,
  announcements: 18,
};

export const MOCK_EVENTS: ClubEvent[] = [
  {
    id: 'ev-001',
    club_id: 'mock-cie-001',
    name: 'CIE Annual Startup Pitch Competition',
    description:
      'Present your startup idea to a panel of industry judges and investors. Top 3 teams win seed funding and incubation support.',
    event_date: '2026-05-20',
    event_time: '09:00',
    venue: 'Main Auditorium, MLRIT',
    eligibility: 'All years',
    max_participants: 120,
    registration_deadline: '2026-05-17',
    status: 'Upcoming',
    created_at: '2026-05-01T10:00:00Z',
  },
  {
    id: 'ev-002',
    club_id: 'mock-cie-001',
    name: 'AI & Machine Learning Workshop',
    description:
      'Hands-on session covering Python, scikit-learn, and building your first ML model from scratch. Bring your laptop.',
    event_date: '2026-05-15',
    event_time: '10:00',
    venue: 'CS Lab 3, Block B',
    eligibility: '2nd year and above',
    max_participants: 60,
    registration_deadline: '2026-05-13',
    status: 'Upcoming',
    created_at: '2026-04-28T08:00:00Z',
  },
  {
    id: 'ev-003',
    club_id: 'mock-cie-001',
    name: 'Design Thinking Bootcamp',
    description:
      'A 2-day intensive bootcamp on human-centered design methodology. Build empathy maps, prototypes, and present solutions.',
    event_date: '2026-05-10',
    event_time: '09:30',
    venue: 'Seminar Hall 2, Block A',
    eligibility: 'All students',
    max_participants: 80,
    registration_deadline: '2026-05-08',
    status: 'Ongoing',
    created_at: '2026-04-20T09:00:00Z',
  },
  {
    id: 'ev-004',
    club_id: 'mock-cie-001',
    name: 'Hackathon 3.0 – Build for Impact',
    description:
      '24-hour hackathon challenging teams to build solutions for real-world social or technical problems. Prizes worth ₹1,00,000.',
    event_date: '2026-06-05',
    event_time: '08:00',
    venue: 'Sports Complex & Labs',
    eligibility: 'Teams of 3–4 students',
    max_participants: 200,
    registration_deadline: '2026-05-30',
    status: 'Upcoming',
    created_at: '2026-04-15T07:00:00Z',
  },
  {
    id: 'ev-005',
    club_id: 'mock-cie-001',
    name: 'Industry Connect: FAANG Panel Discussion',
    description:
      'Panel discussion with senior engineers from top product companies. Includes Q&A, career advice, and a networking session.',
    event_date: '2026-04-28',
    event_time: '14:00',
    venue: 'Main Auditorium, MLRIT',
    eligibility: '3rd & 4th year',
    max_participants: 300,
    registration_deadline: null,
    status: 'Completed',
    created_at: '2026-04-10T10:00:00Z',
  },
  {
    id: 'ev-006',
    club_id: 'mock-cie-001',
    name: 'Web3 & Blockchain Seminar',
    description:
      'Introduction to decentralized applications, smart contracts on Ethereum, and the evolving landscape of Web3.',
    event_date: '2026-04-15',
    event_time: '11:00',
    venue: 'Seminar Hall 1, Block C',
    eligibility: 'All students',
    max_participants: 100,
    registration_deadline: null,
    status: 'Completed',
    created_at: '2026-04-01T10:00:00Z',
  },
  {
    id: 'ev-007',
    club_id: 'mock-cie-001',
    name: 'Open Source Contribution Sprint',
    description:
      'Guided session on contributing to real open-source projects. Mentors will help participants make their first pull request.',
    event_date: '2026-06-14',
    event_time: '10:00',
    venue: 'CS Lab 1, Block B',
    eligibility: '1st year and above',
    max_participants: 50,
    registration_deadline: '2026-06-12',
    status: 'Upcoming',
    created_at: '2026-05-01T08:00:00Z',
  },
];

export const MOCK_ANNOUNCEMENTS: ClubAnnouncement[] = [
  {
    id: 'ann-001',
    club_id: 'mock-cie-001',
    title: 'CIE Recruitment 2026 – Applications Now Open!',
    body: 'We are looking for passionate and driven students to join the CIE Club core team for AY 2026-27. Open positions: Technical Lead, Marketing Lead, Design Lead, and Event Coordinator. Last date to apply: May 18th, 2026. Apply via the Recruitment tab.',
    is_active: true,
    created_at: '2026-05-05T10:00:00Z',
  },
  {
    id: 'ann-002',
    club_id: 'mock-cie-001',
    title: 'CIE Wins Best Innovation Club – State Level Award',
    body: 'We are thrilled to announce that CIE Club has been recognized as the Best Innovation Club at the Telangana State Inter-College Tech Fest 2026. This achievement reflects the dedication of every member. Congratulations team!',
    is_active: true,
    created_at: '2026-05-02T12:00:00Z',
  },
  {
    id: 'ann-003',
    club_id: 'mock-cie-001',
    title: 'New Partnership with TechMahindra – Internship Opportunities',
    body: 'CIE Club has officially partnered with TechMahindra to provide internship and pre-placement opportunities for our members. Eligible students in 3rd year will receive details via email by May 10th.',
    is_active: true,
    created_at: '2026-04-28T09:00:00Z',
  },
  {
    id: 'ann-004',
    club_id: 'mock-cie-001',
    title: 'Startup Pitch Competition – Registration Deadline Extended',
    body: "Due to popular demand, the registration deadline for the Annual Startup Pitch Competition has been extended to May 17th, 2026. If you have been working on an idea, now is the time to bring it forward. Don't miss the opportunity!",
    is_active: true,
    created_at: '2026-04-25T15:00:00Z',
  },
  {
    id: 'ann-005',
    club_id: 'mock-cie-001',
    title: 'Monthly Meetup – May Edition (May 12th, 4:00 PM)',
    body: 'Join us for our monthly community meetup on May 12th at 4:00 PM in Seminar Hall 2. Agenda: project demos by 3 student teams, a 15-minute lightning talk by a guest from the industry, and an open networking session. All members are encouraged to attend.',
    is_active: true,
    created_at: '2026-04-20T11:00:00Z',
  },
  {
    id: 'ann-006',
    club_id: 'mock-cie-001',
    title: 'Hackathon 3.0 Team Registration Open',
    body: 'Team registrations for CIE Hackathon 3.0 – Build for Impact (June 5th) are now live. Form a team of 3–4 members and register before May 30th. Theme details and problem statements will be released on May 20th.',
    is_active: true,
    created_at: '2026-04-18T10:00:00Z',
  },
];

export const MOCK_MEMBERS: ClubMember[] = [
  { id: 'm-001', club_id: 'mock-cie-001', roll_number: '22R25A0501', student_name: 'Arjun Sharma', added_at: '2024-08-05T10:00:00Z' },
  { id: 'm-002', club_id: 'mock-cie-001', roll_number: '22R25A0402', student_name: 'Priya Nair', added_at: '2024-08-06T10:00:00Z' },
  { id: 'm-003', club_id: 'mock-cie-001', roll_number: '23R25A0503', student_name: 'Rohan Mehta', added_at: '2024-08-07T10:00:00Z' },
  { id: 'm-004', club_id: 'mock-cie-001', roll_number: '22R25A1701', student_name: 'Divya Reddy', added_at: '2024-08-08T10:00:00Z' },
  { id: 'm-005', club_id: 'mock-cie-001', roll_number: '23R25A0301', student_name: 'Karan Patel', added_at: '2024-08-09T10:00:00Z' },
  { id: 'm-006', club_id: 'mock-cie-001', roll_number: '22R25A0504', student_name: 'Sneha Iyer', added_at: '2024-09-01T10:00:00Z' },
  { id: 'm-007', club_id: 'mock-cie-001', roll_number: '23R25A0404', student_name: 'Vikram Singh', added_at: '2024-09-02T10:00:00Z' },
  { id: 'm-008', club_id: 'mock-cie-001', roll_number: '24R25A0501', student_name: 'Ananya Krishnan', added_at: '2024-09-03T10:00:00Z' },
  { id: 'm-009', club_id: 'mock-cie-001', roll_number: '22R25A0505', student_name: 'Siddharth Rao', added_at: '2024-09-10T10:00:00Z' },
  { id: 'm-010', club_id: 'mock-cie-001', roll_number: '23R25A1702', student_name: 'Meera Pillai', added_at: '2024-09-15T10:00:00Z' },
  { id: 'm-011', club_id: 'mock-cie-001', roll_number: '22R25A0302', student_name: 'Harsh Tiwari', added_at: '2024-10-01T10:00:00Z' },
  { id: 'm-012', club_id: 'mock-cie-001', roll_number: '24R25A0402', student_name: 'Kavya Menon', added_at: '2024-10-05T10:00:00Z' },
  { id: 'm-013', club_id: 'mock-cie-001', roll_number: '23R25A0506', student_name: 'Nikhil Desai', added_at: '2024-10-12T10:00:00Z' },
  { id: 'm-014', club_id: 'mock-cie-001', roll_number: '22R25A1703', student_name: 'Pooja Varma', added_at: '2024-11-01T10:00:00Z' },
  { id: 'm-015', club_id: 'mock-cie-001', roll_number: '24R25A0302', student_name: 'Aditya Joshi', added_at: '2024-11-08T10:00:00Z' },
  { id: 'm-016', club_id: 'mock-cie-001', roll_number: '22R25A0507', student_name: 'Riya Chopra', added_at: '2024-11-15T10:00:00Z' },
  { id: 'm-017', club_id: 'mock-cie-001', roll_number: '23R25A0405', student_name: 'Tanmay Bose', added_at: '2024-12-01T10:00:00Z' },
  { id: 'm-018', club_id: 'mock-cie-001', roll_number: '24R25A1701', student_name: 'Ishaan Gupta', added_at: '2025-01-10T10:00:00Z' },
  { id: 'm-019', club_id: 'mock-cie-001', roll_number: '23R25A0303', student_name: 'Shreya Nandakumar', added_at: '2025-01-20T10:00:00Z' },
  { id: 'm-020', club_id: 'mock-cie-001', roll_number: '24R25A0508', student_name: 'Varun Sethi', added_at: '2025-02-05T10:00:00Z' },
];

export const MOCK_APPLICATIONS: ClubApplication[] = [
  {
    id: 'app-001', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Rahul Verma', email: 'rahul.verma@mlrit.ac.in', phone: '9876543210',
    department: 'CSE', year: '2nd Year',
    skills: 'Python, React, Machine Learning',
    resume_url: null,
    why_join: 'I want to contribute to CIE\'s technical initiatives and learn from industry experts. I believe hands-on project work through CIE will accelerate my growth as an engineer.',
    experience: 'Built 3 personal projects including a real-time chat app and a recommender system. Participated in 2 college hackathons.',
    github_url: 'https://github.com/rahulverma', linkedin_url: 'https://linkedin.com/in/rahulverma', portfolio_url: null,
    status: 'Pending', created_at: '2026-05-06T10:00:00Z', updated_at: '2026-05-06T10:00:00Z',
  },
  {
    id: 'app-002', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Anjali Sharma', email: 'anjali.sharma@mlrit.ac.in', phone: '9123456789',
    department: 'ECE', year: '3rd Year',
    skills: 'UI/UX Design, Figma, Adobe XD, HTML/CSS, Branding',
    resume_url: null,
    why_join: 'Design is my passion and I want to bring creative, user-centered solutions to real problems through CIE\'s projects and events.',
    experience: 'Won 1st place at state-level UI/UX design competition 2025. Worked with 2 freelance clients on product design.',
    github_url: null, linkedin_url: 'https://linkedin.com/in/anjalish', portfolio_url: 'https://anjalidesigns.netlify.app',
    status: 'Shortlisted', created_at: '2026-05-05T14:00:00Z', updated_at: '2026-05-07T10:00:00Z',
  },
  {
    id: 'app-003', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Karthik Nambiar', email: 'karthik.nambiar@mlrit.ac.in', phone: '9988776655',
    department: 'CSE', year: '3rd Year',
    skills: 'Node.js, Express, PostgreSQL, Docker, Kubernetes',
    resume_url: null,
    why_join: 'I want to apply my backend engineering skills to build scalable products for CIE initiatives and mentor junior members.',
    experience: 'Completed SDE internship at a Hyderabad startup for 6 months. Built and deployed a SaaS tool currently used by 200+ daily active users.',
    github_url: 'https://github.com/karthiknambiar', linkedin_url: 'https://linkedin.com/in/karthiknambiar', portfolio_url: null,
    status: 'Selected', created_at: '2026-05-04T11:00:00Z', updated_at: '2026-05-08T09:00:00Z',
  },
  {
    id: 'app-004', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Sneha Bhatt', email: 'sneha.bhatt@mlrit.ac.in', phone: '9567890123',
    department: 'IT', year: '2nd Year',
    skills: 'Content Writing, Social Media Management, Canva, Video Editing',
    resume_url: null,
    why_join: 'I want to grow CIE\'s social media presence and create compelling content that showcases our events and achievements.',
    experience: 'College newsletter editor for 2 years. Instagram reel creator with a following of 5K+ on personal handle.',
    github_url: null, linkedin_url: 'https://linkedin.com/in/snehabh', portfolio_url: null,
    status: 'Pending', created_at: '2026-05-06T09:00:00Z', updated_at: '2026-05-06T09:00:00Z',
  },
  {
    id: 'app-005', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Arun Nair', email: 'arun.nair@mlrit.ac.in', phone: '9871234560',
    department: 'EEE', year: '2nd Year',
    skills: 'Arduino, IoT, C++, Embedded Systems, Raspberry Pi',
    resume_url: null,
    why_join: 'I want to build hardware-software integrated projects and represent MLRIT at national technology expos.',
    experience: 'Participated in Smart India Hackathon 2025. Built an IoT-based smart irrigation system with automated sensor control.',
    github_url: 'https://github.com/arunnair', linkedin_url: null, portfolio_url: null,
    status: 'Rejected', created_at: '2026-05-03T16:00:00Z', updated_at: '2026-05-07T14:00:00Z',
  },
  {
    id: 'app-006', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Preethi Subramaniam', email: 'preethi.subra@mlrit.ac.in', phone: '9443322110',
    department: 'CSE', year: '1st Year',
    skills: 'Python, Data Analysis, Tableau, SQL',
    resume_url: null,
    why_join: "I'm excited to learn from seniors, contribute to data-driven events, and develop leadership and communication skills early in my college journey.",
    experience: 'No prior club experience but completed Python, Data Science, and SQL courses on Coursera. Ranked in top 5% of class.',
    github_url: null, linkedin_url: null, portfolio_url: null,
    status: 'Pending', created_at: '2026-05-07T08:00:00Z', updated_at: '2026-05-07T08:00:00Z',
  },
  {
    id: 'app-007', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Mohammed Farhan', email: 'farhan.m@mlrit.ac.in', phone: '9712345678',
    department: 'CSE', year: '3rd Year',
    skills: 'Android Development, Kotlin, Firebase, REST APIs',
    resume_url: null,
    why_join: 'Mobile-first solutions are the future — I want to lead a mobile development vertical within CIE and build apps that students actually use.',
    experience: 'Published 2 apps on the Google Play Store with a combined 1,500+ downloads. One app was featured in a college newsletter.',
    github_url: 'https://github.com/farhanm', linkedin_url: 'https://linkedin.com/in/mohammedfarhan', portfolio_url: null,
    status: 'Shortlisted', created_at: '2026-05-05T10:30:00Z', updated_at: '2026-05-07T12:00:00Z',
  },
  {
    id: 'app-008', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Lavanya Reddy', email: 'lavanya.reddy@mlrit.ac.in', phone: '9600112233',
    department: 'IT', year: '3rd Year',
    skills: 'Project Management, MS Excel, Communication, Event Planning',
    resume_url: null,
    why_join: 'I have strong organizational and communication skills and want to coordinate CIE\'s flagship events to help them run smoothly.',
    experience: 'Cultural committee head for 2024-25. Coordinated 4 large-scale college fests with 1000+ attendees. Managed a team of 20 volunteers.',
    github_url: null, linkedin_url: 'https://linkedin.com/in/lavanyareddy', portfolio_url: null,
    status: 'Selected', created_at: '2026-05-04T13:00:00Z', updated_at: '2026-05-08T11:00:00Z',
  },
  {
    id: 'app-009', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Devansh Mishra', email: 'devansh.mishra@mlrit.ac.in', phone: '9315678901',
    department: 'CSE', year: '2nd Year',
    skills: 'Full-Stack Development, React, TypeScript, MongoDB',
    resume_url: null,
    why_join: 'I want to build real, impactful products alongside talented peers and grow as a full-stack developer while contributing to CIE\'s technical projects.',
    experience: 'Contributed to 2 open-source projects. Built a hostel room-swap platform used by 400+ students at MLRIT.',
    github_url: 'https://github.com/devansh-m', linkedin_url: 'https://linkedin.com/in/devanshm', portfolio_url: 'https://devanshm.dev',
    status: 'Pending', created_at: '2026-05-07T11:00:00Z', updated_at: '2026-05-07T11:00:00Z',
  },
  {
    id: 'app-010', club_id: 'mock-cie-001', student_id: null,
    full_name: 'Nandini Kaur', email: 'nandini.kaur@mlrit.ac.in', phone: '9888001122',
    department: 'ECE', year: '2nd Year',
    skills: 'Public Speaking, Event Management, MS PowerPoint, Leadership',
    resume_url: null,
    why_join: 'I want to develop leadership skills and contribute to making CIE\'s events more engaging and accessible to all students.',
    experience: 'NSS volunteer for 2 years. Presented at 3 inter-college science fairs. Won best speaker at the MLRIT debate club in 2025.',
    github_url: null, linkedin_url: 'https://linkedin.com/in/nandinikaur', portfolio_url: null,
    status: 'Shortlisted', created_at: '2026-05-06T15:00:00Z', updated_at: '2026-05-08T10:00:00Z',
  },
];

export const MOCK_TEAM: TeamMember[] = [
  { name: 'Arjun Sharma', role: 'President', department: 'CSE', year: '3rd Year' },
  { name: 'Priya Nair', role: 'Vice President', department: 'ECE', year: '3rd Year' },
  { name: 'Rohan Mehta', role: 'Technical Lead', department: 'CSE', year: '2nd Year' },
  { name: 'Divya Reddy', role: 'Event Lead', department: 'IT', year: '3rd Year' },
  { name: 'Karan Patel', role: 'Media Lead', department: 'EEE', year: '2nd Year' },
  { name: 'Sneha Iyer', role: 'Design Lead', department: 'CSE', year: '2nd Year' },
  { name: 'Vikram Singh', role: 'Finance Lead', department: 'ECE', year: '3rd Year' },
];

export const MOCK_ACHIEVEMENTS: ClubAchievement[] = [
  {
    title: 'National Hackathon Champions',
    description: 'First place at Smart India Hackathon 2025, competing against 500+ teams nationwide.',
    year: '2025',
    icon: 'trophy',
  },
  {
    title: 'Best Innovation Club',
    description: 'Recognized as the most active innovation club at the Telangana State Tech Fest 2025.',
    year: '2025',
    icon: 'star',
  },
  {
    title: '500+ Mentorship Hours',
    description: 'Delivered over 500 hours of structured peer-to-peer mentorship across 4 academic batches.',
    year: '2024',
    icon: 'book',
  },
  {
    title: '12 Industry Partnerships',
    description: 'Active collaborations with 12 tech companies providing internships and live project opportunities.',
    year: '2024',
    icon: 'globe',
  },
  {
    title: '₹5L+ Seed Funding Raised',
    description: 'Helped 3 student startups raise seed funding through CIE\'s investor network and pitch events.',
    year: '2024',
    icon: 'zap',
  },
  {
    title: 'AICTE Innovation Award',
    description: 'Recipient of the National Student Innovation Award by the All India Council for Technical Education.',
    year: '2023',
    icon: 'award',
  },
];

export const MOCK_GALLERY: GalleryItem[] = [
  {
    id: 'gal-001',
    title: 'Hackathon 3.0 Kickoff',
    caption: 'Opening ceremony with 200+ participants from across the college',
    type: 'photo',
    date: '2026-04-05',
    color: '#6366f1',
    event: 'Hackathon 3.0',
  },
  {
    id: 'gal-002',
    title: 'AI Workshop Session',
    caption: 'Hands-on ML model building with Python and scikit-learn',
    type: 'photo',
    date: '2026-03-20',
    color: '#3b82f6',
    event: 'AI Workshop',
  },
  {
    id: 'gal-003',
    title: 'Industry Panel – Q&A',
    caption: 'Live Q&A with engineers from leading product companies',
    type: 'video',
    date: '2026-03-10',
    color: '#10b981',
    event: 'Industry Connect',
  },
  {
    id: 'gal-004',
    title: 'Award Ceremony 2025',
    caption: 'Receiving the Best Innovation Club award at the state level',
    type: 'photo',
    date: '2025-12-15',
    color: '#f59e0b',
    event: 'Annual Award Ceremony',
  },
  {
    id: 'gal-005',
    title: 'Design Thinking Bootcamp',
    caption: 'Teams presenting their prototype solutions to the panel',
    type: 'photo',
    date: '2025-11-22',
    color: '#8b5cf6',
    event: 'Design Bootcamp',
  },
  {
    id: 'gal-006',
    title: 'SIH 2025 – Winners',
    caption: 'CIE team celebrating the first-place finish at Smart India Hackathon',
    type: 'photo',
    date: '2025-08-30',
    color: '#ef4444',
    event: 'Smart India Hackathon',
  },
];

export const MOCK_ANALYTICS: AnalyticsData = {
  overview: {
    totalMembers: 87,
    activeEvents: 3,
    totalEvents: 24,
    pendingApplications: 12,
    acceptedApplications: 18,
    totalApplications: 35,
  },
  memberGrowth: [
    { month: "Oct '25", members: 62 },
    { month: "Nov '25", members: 67 },
    { month: "Dec '25", members: 70 },
    { month: "Jan '26", members: 74 },
    { month: "Feb '26", members: 79 },
    { month: "Mar '26", members: 82 },
    { month: "Apr '26", members: 85 },
    { month: "May '26", members: 87 },
  ],
  eventParticipation: [
    { event: 'Hackathon', participants: 148, capacity: 200 },
    { event: 'AI Workshop', participants: 56, capacity: 60 },
    { event: 'Pitch Comp', participants: 98, capacity: 120 },
    { event: 'Design Boot', participants: 72, capacity: 80 },
    { event: 'FAANG Panel', participants: 280, capacity: 300 },
  ],
  recruitmentFunnel: [
    { name: 'Applied', value: 35, color: '#6366f1' },
    { name: 'Shortlisted', value: 22, color: '#3b82f6' },
    { name: 'Selected', value: 18, color: '#22c55e' },
    { name: 'Rejected', value: 8, color: '#ef4444' },
  ],
  engagementTrend: [
    { month: "Oct '25", events: 3, announcements: 4, members: 5 },
    { month: "Nov '25", events: 2, announcements: 3, members: 3 },
    { month: "Dec '25", events: 4, announcements: 5, members: 4 },
    { month: "Jan '26", events: 5, announcements: 6, members: 7 },
    { month: "Feb '26", events: 3, announcements: 4, members: 5 },
    { month: "Mar '26", events: 4, announcements: 5, members: 6 },
    { month: "Apr '26", events: 6, announcements: 7, members: 5 },
    { month: "May '26", events: 3, announcements: 5, members: 4 },
  ],
  recentActivity: [
    {
      id: 'ra-1',
      type: 'member_joined',
      message: 'Rahul Verma joined the club',
      time: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      id: 'ra-2',
      type: 'application_submitted',
      message: 'Preethi Subramaniam submitted an application',
      time: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'ra-3',
      type: 'event_created',
      message: 'Event "Hackathon 3.0 – Build for Impact" was created',
      time: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: 'ra-4',
      type: 'announcement_posted',
      message: 'Announcement "CIE Recruitment 2026 – Applications Now Open!" was posted',
      time: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 'ra-5',
      type: 'member_joined',
      message: 'Karthik Nambiar was accepted and joined the core team',
      time: new Date(Date.now() - 172800000).toISOString(),
    },
    {
      id: 'ra-6',
      type: 'event_created',
      message: 'Event "AI & Machine Learning Workshop" was created',
      time: new Date(Date.now() - 259200000).toISOString(),
    },
  ],
};
